name: TargetEngine
description: Target is a simple toolbox to build Games, UI and etc.
version: 0.1.0
environment:
  sdk: '^3.10.0'
dependencies:
  ffi: ^2.1.5
  collection: ^1.19.1
dev_dependencies:
  ffigen: ^20.1.1
